production:
  web:
#    google_client_id:           ENV['GOOGLE_CLIENT_ID']
#    google_project_id:          ENV['GOOGLE_PROJECT_ID']
#    google_auth_uri:            ENV['GOOGLE_AUTH_URI']
#    google_token_uri:           ENV['GOOGLE_TOKEN_URI']
#    google_auth_provider:       ENV['GOOGLE_AUTH_PROVIDER']
#    google_client_secret:       ENV['GOOGLE_CLIENT_SECRET']
#    google_redirect_uris:       ENV['GOOGLE_REDIRECT_URIS']
#    google_javascript_origins:  ENV['GOOGLE_JAVASCRIPT_ORIGINS']
  server:
#    google_client_id:           ENV['GOOGLE_CLIENT_ID']
#    google_project_id:          ENV['GOOGLE_PROJECT_ID']
#    google_auth_uri:            ENV['GOOGLE_AUTH_URI']
#    google_token_uri:           ENV['GOOGLE_TOKEN_URI']
#    google_auth_provider:       ENV['GOOGLE_AUTH_PROVIDER']
#    google_client_secret:       ENV['GOOGLE_CLIENT_SECRET']
#    google_redirect_uris:       ENV['GOOGLE_REDIRECT_URIS']
#    google_javascript_origins:  ENV['GOOGLE_JAVASCRIPT_ORIGINS']

development:
  web:
#    google_client_id:           ENV['GOOGLE_CLIENT_ID']
#    google_project_id:          ENV['GOOGLE_PROJECT_ID']
#    google_auth_uri:            ENV['GOOGLE_AUTH_URI']
#    google_token_uri:           ENV['GOOGLE_TOKEN_URI']
#    google_auth_provider:       ENV['GOOGLE_AUTH_PROVIDER']
#    google_client_secret:       ENV['GOOGLE_CLIENT_SECRET']
#    google_redirect_uris:       ENV['GOOGLE_REDIRECT_URIS']
#    google_javascript_origins:  ENV['GOOGLE_JAVASCRIPT_ORIGINS']
  server:
#    google_client_id:           ENV['GOOGLE_CLIENT_ID']
#    google_project_id:          ENV['GOOGLE_PROJECT_ID']
#    google_auth_uri:            ENV['GOOGLE_AUTH_URI']
#    google_token_uri:           ENV['GOOGLE_TOKEN_URI']
#    google_auth_provider:       ENV['GOOGLE_AUTH_PROVIDER']
#    google_client_secret:       ENV['GOOGLE_CLIENT_SECRET']
#    google_javascript_origins:  ENV['GOOGLE_JAVASCRIPT_ORIGINS']
